### ISSUE TITLE
Create sample of routes to analyse

### ISSUE THREAD

**Issue by Robinlovelace** [CatchDat/TravelAIR#3]
Suggest 10 routes in the first instance. Suggest changing the times on them.

**Comment by eyesofbambi** [comment]
Created script for randomly selecting journeys with a minimum number of observations per journey. Selected random journey files can be found in private data repo at https://github.com/eyesofbambi/travelAIRData
Script is at https://github.com/CatchDat/TravelAIR/blob/master/R/selectRandomJourneys.R

**Comment by Robinlovelace** [comment]
Great work, many thanks!
